name: Markdown Links Check
# runs every monday at 9 am
on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * 1"

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # checks all broken links in markdown files from /chapter_8/guides
      - uses: gaurav-nelson/github-action-markdown-link-check@a996638015fbc9ef96beef1a41bbad7df8e06154
